name: CI/CD to DigitalOcean Droplet

on:
  push:
    branches: [ "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into GCP VM and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd HRIS
            git pull
            rm -rf dist
            npm run build
            pm2 restart all
            sudo systemctl restart nginx